/*
 * 389. Find the Difference
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 * */

#include <string>

class Solution {
public:
    char findTheDifference(std::string s, std::string t) {
        std::sort(s.begin(), s.end());
        std::sort(t.begin(), t.end());
        for (size_t i = 0; i < s.size(); ++i)
            if (s[i] != t[i])
                return t[i];
        return t.back();
    }
};

int main() {
	Solution s;
	const bool res1 = s.findTheDifference("abcd", "qdacb") == 'q';
	const bool res2 = s.findTheDifference("abcd", "dacbf") == 'f';
    return 0;
}